apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: eranzaksh/movieweb-app
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: eranzaksh
  lifecycle: development
  system: project-x

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: project-x
    description: Handy tools to keep artists in the loop
spec:
    owner: artist-relations-team
    domain: artists