apiVersion: scaffolder.backstage.io/v1alpha1
kind: Template
metadata:
  name: python-app
  title: Python Application
  description: Scaffold a simple Python app with a basic structure.
spec:
  owner: guests
  type: service
  parameters:
    - title: "App Name"
      description: "The name of your Python app"
      type: string
      required: true
      default: "my-python-app"
    - title: "Repository URL"
      description: "The GitHub repository URL where this app will be created"
      type: string
      required: true
  steps:
    - id: fetch:cookiecutter
      name: Generate Project from Cookiecutter Template
      action: fetch:cookiecutter
      input:
        url: "https://github.com/cookiecutter-flask/cookiecutter-flask"
        values:
          project_name: ${{ parameters.AppName }}
    - id: publish:github
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.RepositoryURL }}
        description: "A new Python app generated by Backstage"
